module.exports = {
    AddReactions: "Reaktionen hinzufügen",
    Administrator: "Administrator",
    AttachFiles: "Dateien anhängen",
    BanMembers: "Mitglieder bannen",
    ChangeNickname: "Nickname ändern",
    Connect: "Verbinden",
    CreateInstantInvite: "Einladung erstellen",
    CreatePrivateThreads: "Private Threads erstellen",
    CreatePublicThreads: "Öffentliche Threads erstellen",
    DeafenMembers: "Mitglieder stummschalten",
    EmbedLinks: "Links einbetten",
    KickMembers: "Mitglieder kicken",
    ManageChannels: "Kanäle verwalten",
    ManageEmojisAndStickers: "Emojis und Sticker verwalten",
    ManageEvents: "Events verwalten",
    ManageGuild: "Server verwalten",
    ManageMessages: "Nachrichten verwalten",
    ManageNicknames: "Nicknames verwalten",
    ManageRoles: "Rollen verwalten",
    ManageThreads: "Threads verwalten",
    ManageWebhooks: "Webhooks verwalten",
    MentionEveryone: "Erwähne @everyone, @here und \"Alle Rollen\"",
    ModerateMembers: "Mitglieder in Timeout versetzen",
    MoveMembers: "Mitglieder verschieben",
    MuteMembers: "Ein- und Ausgabe von Mitgliedern deaktivieren",
    PrioritySpeaker: "Very Important Speaker",
    ReadMessageHistory: "Nachrichtenverlauf anzeigen",
    RequestToSpeak: "Redeanfrage",
    SendMessages: "Nachrichten senden",
    SendMessagesInThreads: "Nachrichten in Threads senden",
    SendTTSMessages: "Text-zu-Sprache Nachrichten senden",
    Speak: "Sprechen",
    Stream: "Video",
    UseApplicationCommands: "Anwendungsbefehle verwenden",
    UseEmbeddedActivities: "Aktivitäten nutzen",
    UseExternalEmojis: "Externe Emojis verwenden",
    UseExternalStickers: "Externe Sticker verwenden",
    ViewAuditLog: "Audit-Log einsehen",
    ViewChannel: "Channel anzeigen",
    ViewGuildInsights: "Server-Einblicke anzeigen",
};

